# Generated by Django 4.0.4 on 2022-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_project_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
